storing secrets as enviromental variables
preview-code/backend pull request #36
Opened 2017-04-25 14:46 UTC by eanker

Uses the stored environmental variables.

The are configured on the server.
Locally, you have to add them to the run configuration with names:
`INTEGRATION_ID`
`INTEGRATION_KEY`
`WEBHOOK_SECRET`

2017-04-25 15:46 UTC, txsmith requested changes

2017-04-25 15:46 UTC, txsmith commented on src/main/java/previewcode/backend/api/filter/GitHubAccessTokenFilter.java
> -                logger.warn("Could not verify GitHub webhook call:", e);
Why did I remove this? - Eva 2017

2017-04-25 15:46 UTC, txsmith commented on pom.xml
> +        <!--<testSourceDirectory>src/test/java</testSourceDirectory>-->
:(

2017-04-26 07:49 UTC, txsmith approved these changes

2017-04-26 07:49 UTC, eanker commented
Added the run-config to the resource folder, so you can import that an you will have the correct values.
If the files reside in `resource`. You have to create a file named `integration-id.txt` which containes the integration id.

2017-04-26 07:51 UTC, txsmith requested changes

2017-04-26 07:51 UTC, txsmith commented on src/main/resources/run-config.xml
> +              <entry key="INTEGRATION_ID" value="src/main/resources/integration-id.txt" />
These should not be inside the resources directory because the compiler will now include the keys in the jar when you build the project

2017-04-26 07:59 UTC, eanker commented on src/main/resources/run-config.xml
> +              <entry key="INTEGRATION_ID" value="src/main/resources/integration-id.txt" />
This was the location they where already in, but I have changed it.
You now have to make in the top directory a folder named `secrets` and put it there.
I couldn't think of a better name.

2017-04-26 08:00 UTC, txsmith approved these changes

2017-04-26 08:01 UTC, merged