Added the backend for handeling isApproved
preview-code/backend pull request #51
Opened 2017-05-29 08:36 UTC by eanker

Backend for preview-code/minimal-frontend#43

TODO: webhook, but that will be a separate pull request.

2017-05-30 07:21 UTC, txsmith requested changes

2017-05-30 07:21 UTC, txsmith commented on src/main/java/previewcode/backend/DTO/ApprovedGroup.java
> +    public Map<String, String> hunks;
Can you add `@JsonProperty` annotations here?

2017-05-30 07:22 UTC, txsmith requested changes

2017-05-30 07:22 UTC, txsmith commented on src/main/java/previewcode/backend/DTO/ApprovedGroup.java
> +    public Map<String, String> hunks;
And a constructor with `@JsonCreator` and `@JsonProperty` on the arguments

2017-05-30 07:42 UTC, txsmith requested changes

2017-05-30 07:42 UTC, txsmith commented on src/main/java/previewcode/backend/DTO/ApprovedGroup.java
> +    public String approved;
Should be `Option<Boolean>`

2017-05-30 07:42 UTC, txsmith commented on src/main/java/previewcode/backend/DTO/IsApproved.java
> +    public String approved;
Should be `Option<Boolean>`

2017-06-29 09:43 UTC, closed without merging

2017-06-29 09:44 UTC, eanker commented
replaced by #52